version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cl2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-111dmq2zaul4s"
s3_prefix = "cl2"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
